name: Build and push nodejs app to artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

     # - name: Archive the app
      #  run: tar -czf akram_app.tar.gz .

      - name: Configure artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run:
          npm set registery="$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD"
          #npm login --registry=$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/ --auth-type=web
          #echo "machine $ARTIFACTORY_URL login $ARTIFACTORY_USERNAME password $ARTIFACTORY_PASSWORD" > ~/.netrc

      - name: Push to artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          NPM_CONFIG_TOKEN: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: npm publish #--registry $ARTIFACTORY_URL/artifactory/api/npm/paris-npm/
          #|
          #curl -u "$ARTIFACTORY_USERNAME":"$ARTIFACTORY_PASSWORD" \ -T . \ "$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/akram_app"
